#+title: Readme
* dotfiles for fedora siverblue 💙 doom emacs

🤠: Is it really possible for an Emacs and a Container to be in a relationship?

I went with distrobox rather than building a new Container, as the =fedora-toolbox= already covers much of what I need.
https://github.com/ublue-os/toolboxes/

** TODO Tasks
- install chezmoi.el
- add local hook: after tangling, optionally update chezmoi?
- add local variable to either tangle here or to intended target.
- See if it makes sense to install packages
  https://www.chezmoi.io/user-guide/advanced/install-packages-declaratively/

If making changes:
1. Modify femacs.org, tangle.
2. chezmoi update.
   the /source/ femacs.org along with any modified tangled files
3. git add, stage, commit, push

If backing up or restoring:
1. pull
2. chezmoi diff
3. chezmoi apply
** TODO Inbox
*** Comparing Brew

Host after uninstalling texlive.
#+begin_example
atuin	       bzip2		dysk   gmp	  libgit2     libxcrypt  openssl@3    shellcheck  yq
basedpyright   c-ares		expat  icu4c@76   libmpc      lz4	 pandoc       sqlite	  yt-dlp
bash	       ca-certificates	eza    isl	  libnghttp2  mpdecimal  pcre2	      tealdeer	  zlib
bat	       certifi		fd     krb5	  libnsl      mpfr	 podlet       trash-cli   zoxide
berkeley-db@5  chezmoi		gcc    libedit	  libssh2     ncurses	 python@3.13  ugrep	  zstd
binutils       devcontainer	gh     libffi	  libtirpc    node	 readline     unzip
brotli	       direnv		glab   libgccjit  libuv       oniguruma  ripgrep      xz
#+end_example

bluefin-cli after installing cowsay and texlive. why is it bigger?
#+begin_example
acl		 gettext      libarchive    libtirpc	  libxrandr	openexr		       tesseract
alsa-lib	 ghostscript  libavif	    libtommath	  libxrender	openjdk		       texlive
aom		 giflib       libb2	    libtool	  libxshmfence	openjpeg	       unzip
berkeley-db@5	 glib	      libclc	    libunistring  libxt		openssl@3	       util-linux
binutils	 glslang      libde265	    libva	  libxtst	pango		       valgrind
brotli		 gmp	      libdeflate    libvdpau	  libxv		pcre2		       wayland
bzip2		 gperf	      libdrm	    libvmaf	  libxxf86vm	perl		       wayland-protocols
ca-certificates  graphite2    libedit	    libx11	  libyaml	pixman		       webp
cairo		 gzip	      libffi	    libxau	  little-cms2	plotutils	       x265
clisp		 harfbuzz     libheif	    libxaw	  llvm		potrace		       xorgproto
cowsay		 highway      libice	    libxcb	  lm-sensors	pstoedit	       xz
cups		 icu4c@76     libidn	    libxcrypt	  lua		python-packaging       z3
dbus		 imagemagick  liblqr	    libxdmcp	  luajit	python@3.12	       zip
elfutils	 imath	      libnsl	    libxext	  lz4		python@3.13	       zlib
expat		 jasper       libpciaccess  libxfixes	  lzo		readline	       zstd
fontconfig	 jbig2dec     libpng	    libxft	  m4		ruby
freetype	 jpeg-turbo   libraw	    libxi	  mesa		shared-mime-info
fribidi		 jpeg-xl      libsigsegv    libxml2	  mpdecimal	spirv-llvm-translator
gd		 krb5	      libsm	    libxmu	  mpfr		sqlite
gdbm		 leptonica    libtiff	    libxpm	  ncurses	tcl-tk

#+end_example
*** NO Also, what's up with the binaries I have in home? Should I replace those?
I cannot.
*** TODO Upload all this stuff to Git or something.
*** Inspiration
https://github.com/herzenschein/herz-quadlet
*** Nix...?
https://github.com/idlip/d-nix
https://old.reddit.com/r/emacs/comments/1025nja/any_examples_of_a_config_in_org_on_nix/
https://old.reddit.com/r/NixOS/comments/pk8jo0/nix_emacs_orgbabel_src_blocks_has_anyone_got_them/
https://old.reddit.com/r/emacs/comments/16gr2nl/my_emacs_nix_flake_is_now_built_entirely_from_an/
*** IDEA Migrating from org-babel to chezmoi

https://simendsjo.me/blog/20240513200515-migrating_my_systems_from_org_babel_to_chezmoi
*** IDEA chezmoi.el
https://github.com/tuh8888/chezmoi.el
** Design

1. Make changes to the Org file here.
   a. Tangle to Target directory.
      Yes, because I want to see immediate changes.

      If it breaks, I can grab the tangled source without having to revert the config.org. I can revert the config.org as needed by git independently.
      This way, I can also revert changes to the original config.org file.

      If I git commit without re-adding, then the source and literate file are out of sync.

   b. Or Source directory...?
      If I tangle to source directory, then I would have to ~chezmoi apply~ in order to see my changes. Automatically calling this isn't hard to script at all.

     If I git commit without applying, then the source and literate file are still in sync.
     If this breaks, then I can go back to where I need to from git.




What is the pro or con for either approach?
The point of using chezmoi in the first place is so that we can directly grab tangled files that are ready to be used.
**
* Sources
https://github.com/gabyx/dotfiles
https://github.com/fredrdz/dotfiles
https://github.com/topics/chezmoi?o=desc&s=updated

* Justfile
This

* Doom Emacs

config.org tangles to config.el and package.el

I could create a custom script to tangle config.org file from here, maybe.

* Chezmoi

* Femacs
