#+title: doom emacs 💙 uBlue
#+description: Documentation of my config management workflow.
:PROPERTIES:
#+PROPERTY: header-args    :tangle (concat (org-entry-get nil "tangledir" t) (org-element-property :name (org-element-at-point)))
#+PROPERTY: tangledir      ~/.dotfiles/
#+STARTUP: content
:END:

This repo is the home of my system configuration, which follows the uBlue project as much as possible while supporting full Doom Emacs usage, as it can be tricky to understand how to use Emacs in a container paradigm.

- Laptop: [[https://www.notebookcheck.net/Lenovo-Yoga-720-15IKB-7700HQ-FHD-GTX-1050-Laptop-Review.227572.0.html][Lenovo Yoga 720-15 IKB]]
- Host OS: [[https://github.com/ublue-os/bluefin][bluefin]] (Fedora Silverblue), which pushes a containerized approach.
- Key Features:
  - Literate Approach :: The purpose of a literate approach is to *reduce the cognitive load*. Whenever I make changes to my system, it helps to have extensive notes about my journey right next to the configuration!
  - Distrobox [[https://docs.projectbluefin.io/bluefin-dx#pet-containers][pet containers]]:
    - =bluefin-cli= a containerized =homebrew= that shares apps with host and other containers.
    - =femacs= an environment for Doom Emacs and any optional package requirements.

I manage configuration files in this repo using Emacs Org Mode and Chezmoi. This allows me to modify all my configurations in one folder, while exporting and ensuring changes are backed up with two commands:

: doom +org tangle ~/.dotfiles
: chezmoi apply

* Using my configuration
:sources:
https://leanpub.com/lit-config/read
https://github.com/gabyx/dotfiles
https://github.com/fredrdz/dotfiles
https://github.com/topics/chezmoi?o=desc&s=updated
:end:

The purpose of a literate approach is to *reduce the cognitive load*. Whenever I make changes to my system, it helps to have extensive notes about my journey right next to the configuration!

In order to make use of this repository, you can either:
  - Make sense of it :: Read through the =.org= files, which will include full context of the information you need and any decisions made.
  - Clone my setup :: Use ~chezmoi~ to directly apply any files in =chezmoi/= to your system. This won't make much sense unless you are me. If you are unfamiliar with chezmoi, see [[https://www.chezmoi.io/quick-start][chezmoi quick start]]

** Justfile Commands
#+begin_src :tangle justfile
default:
    echo 'Hello, world!'

# Assemble distrobox containers
assemble:
  echo 'Assembling and replacing distroboxes ...'
  distrobox assemble create --replace --file distrobox.ini

#+end_src
** Workflow

#+begin_src mermaid
---
title: Usual Workflow, Doom Emacs installed
---

sequenceDiagram
    Participant home as home directory
    Participant source as working directory
    Participant local as local repo
    Participant remote as remote repo

    note over source: Edit .org files as necessary
    source ->> home: doom +org tangle ~/.dotfiles
    home ->> source: chezmoi add <files>

    note over source: Backup to GitHub
    source ->> local: git add
    local ->> remote: git push
#+end_src

I went with distrobox rather than building a new Container, as the =fedora-toolbox= already covers much of what I need.

* License
Released under the [[file:LICENSE][Unlicense]] unless otherwise specified by license files in subfolders.
